### ISSUE TITLE
Osx Issue Port

### ISSUE THREAD

**Issue by domgolonka** [fastogt/pyfastogt#5]
`python3 build_env.py
Build request for platform: macosx(x86_64) created
Device: pc
Traceback (most recent call last):
  File "build_env.py", line 507, in <module>
    request.install_system()
  File "build_env.py", line 290, in install_system
    self._install_package(lib)
  File "/usr/local/lib/python3.7/site-packages/pyfastogt-1.1.0-py3.7.egg/pyfastogt/build_utils.py", line 246, in _install_package
  File "/usr/local/lib/python3.7/site-packages/pyfastogt-1.1.0-py3.7.egg/pyfastogt/system_info.py", line 170, in install_package
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'port': 'port'`

Getting the issue with port on pyfastogt/system_info.py", line 170,

**Comment by domgolonka** [comment]
Nevermind, figured out that you need to install PORT for Mac Osx https://www.macports.org/install.php
